Expand boilerplate and make customizable for different kinds of plugins.
learningequality/cookiecutter-kolibri-plugin pull request #1
Opened 2017-01-31 22:38 UTC by rtibbles

Expands the boilerplate code and makes most options more customizable.

Also cuts out unnecessary code depending on the purpose of the plugin.

2017-01-31 23:08 UTC, rtibbles commented on cookiecutter.json
> +  "license": ["MIT", "GNU GPL v3.0", "Apache Software License 2.0", "The Unlicense"],
Comment from @jamalex that we probably want to remove GPL from here as it makes reusing others' plugins problematic.

Can also collapse to a hard default of MIT that people have to modify if they want to change the license.

2017-02-06 22:43 UTC, christianmemije commented on README.md
> +* You will then be prompted to enter a description, a repository url, and author details..
Extra period.

2017-02-06 22:44 UTC, christianmemije commented on README.md
> +* Select if this plugin is a content renderer plugin, and what content kind and file extension it handles. If you are not creating a content renderer plugin, you may safely ignore these options.
There is no option to add a new content type?

2017-02-06 22:51 UTC, christianmemije commented on {{cookiecutter.plugin_name}}/README.rst
> +4. Then run the commands to install frontend packages in Kolibri, this plugin will have its recursively installed.
Needs clarification.

2017-02-06 22:51 UTC, christianmemije commented on {{cookiecutter.plugin_name}}/README.rst
> +1. Follow the instructions above to installing the plugin for development.
Typo?

2017-02-06 23:15 UTC, christianmemije commented on {{cookiecutter.plugin_name}}/{{cookiecutter.plugin_name}}/assets/src/module.js
> +const RootComponent = require('./vue');
`1:7   error  'RootComponent' is defined but never used  no-unused-vars`

2017-02-06 23:16 UTC, christianmemije commented on {{cookiecutter.plugin_name}}/{{cookiecutter.plugin_name}}/assets/src/module.js
> +      render: createElement => createElement(RootVue),
`21:46  error  'RootVue' is not defined                   no-undef`

2017-02-06 23:17 UTC, christianmemije requested changes
Some lint errors.

2017-02-08 18:27 UTC, rtibbles commented on README.md
> +* Select if this plugin is a content renderer plugin, and what content kind and file extension it handles. If you are not creating a content renderer plugin, you may safely ignore these options.
No, the content types are validated against currently allowed content types in `le-utils`.

2017-02-08 18:28 UTC, rtibbles commented on {{cookiecutter.plugin_name}}/README.rst
> +4. Then run the commands to install frontend packages in Kolibri, this plugin will have its recursively installed.
Should I link to the Kolibri docs?

2017-02-08 18:28 UTC, rtibbles commented on {{cookiecutter.plugin_name}}/README.rst
> +1. Follow the instructions above to installing the plugin for development.
Definitely!

2017-02-08 18:29 UTC, rtibbles commented on {{cookiecutter.plugin_name}}/{{cookiecutter.plugin_name}}/assets/src/module.js
> +const RootComponent = require('./vue');
Good catch.

2017-02-08 18:29 UTC, rtibbles commented on {{cookiecutter.plugin_name}}/{{cookiecutter.plugin_name}}/assets/src/module.js
> +      render: createElement => createElement(RootVue),
Will standardize.

2017-02-08 18:36 UTC, christianmemije commented on {{cookiecutter.plugin_name}}/README.rst
> +4. Then run the commands to install frontend packages in Kolibri, this plugin will have its recursively installed.
*"will have its [dependencies?] recursively installed."

2017-02-16 19:27 UTC, merged